dockarmaiii:
  image: thalhalla/dockarmaiii:${DOCKARMAIII_BRANCH}
  command: ${DOCKARMAIII_COMMAND}
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    HOSTNAME: ${HOSTNAME}
    MAX_PLAYERS: ${MAX_PLAYERS}
    STEAM_GID: 233780
    IP: 0.0.0.0
    PORT: ${PORT}
    PORT2: ${PORT2}
    PORT3: ${PORT3}
    PORT4: ${PORT4}
    MODS: ${DOCKARMAIII_MODS}
    WASTELAND_ENABLED: ${WASTELAND_ENABLED}
    DRYRUN: true
    FORCEUPDATE: true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: ${host_label}
    io.rancher.sidekicks: dockarmaiii-datavolume
    io.rancher.container.pull_image: always
    cron.schedule: "1 40 * * 1 ?"
  ports:
    - "${PORT}:${PORT}/udp"
    - "${PORT2}:${PORT2}/udp"
    - "${PORT3}:${PORT3}/udp"
    - "${PORT4}:${PORT4}/udp"
  volumes_from:
    - dockarmaiii-datavolume
dockarmaiii-datavolume:
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}
    io.rancher.container.start_once: true
    io.rancher.container.pull_image: always
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    HOSTNAME: ${HOSTNAME}
    MAX_PLAYERS: ${MAX_PLAYERS}
    STEAM_GID: 233780
    IP: 0.0.0.0
    PORT: ${PORT}
    MODS: ${DOCKARMAIII_MODS}
    WASTELAND_ENABLED: ${WASTELAND_ENABLED}
  volume_driver: ${VOLUME_DRIVER}
  volumes:
    - ${DATA_VOLUME_NAME}:/data
    - ${CONFIG_VOLUME_NAME}:/home/steam
  image: busybox
  command: /bin/true
