name: Team Fortress 2
description: Rancher Team Fortress 2 dedicated server
version: 0.3.0
category: Thalhalla Game Servers
maintainer: josh@webhosting.coop
license: GPLv3
projectURL: https://github.com/Thalhalla/tf2
