dockarmaiii:
  image: thalhalla/dockarmaiii
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    STEAM_GID: 233780
    IP: ${IP}
    PORT: ${PORT}
    PORT2: ${PORT2}
    PORT3: ${PORT3}
    PORT4: ${PORT4}
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: dockarmaiii-datavolume
  volumes_from:
    - dockarmaiii-datavolume
  ports:
    - "${PORT}:${PORT}/udp"
    - "2303:2303/udp"
    - "2304:2304/udp"
    - "2305:2305/udp"
    - "2344:2344/udp"
    - "2345:2345/udp"
    - "2344:2344"
    - "2345:2345"
dockarmaiii-datavolume:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /home/steam/.steam
    - /home/steam/.local
    - /home/steam/steamcmd
    - /home/steam/Steam
    - /home/steam/SteamLibrary
    - /home/steam/serverfiles
    - /home/steam/log
  entrypoint: /bin/true
  image: busybox
