name: Team Speak 3
description: Rancher Team Speak 3 dedicated server
version: 0.3.1
category: Thalhalla Game Servers
maintainer: josh@webhosting.coop
license: GPLv3
projectURL: https://github.com/Thalhalla/teamspeacker
