7daystodie:
  image: thalhalla/7daystodie:${7DAYSTODIE_BRANCH}
  command: ${7DAYSTODIE_COMMAND}
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    STEAM_FORCE_INSTALL: ${STEAM_FORCE_INSTALL}
    MAX_PLAYERS: ${MAX_PLAYERS}
    ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    HOSTNAME: ${HOSTNAME}
    STEAM_GID: ${STEAM_GID}
    IP: ${IP}
    PORT: ${PORT}
    PORT2: ${PORT2}
    PORT3: ${PORT3}
    PORT4: ${PORT4}
    MODS: ${7DAYSTODIE_MODS}
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: 7daystodie-datavolume
    io.rancher.scheduler.affinity:host_label: ${host_label}
    io.rancher.container.pull_image: always
  volumes_from:
    - 7daystodie-datavolume
  ports:
    - "${PORT}:${PORT}"
    - "${PORT}:${PORT}/udp"
    - "${PORT2}:${PORT2}"
    - "${PORT2}:${PORT2}/udp"
    - "${PORT3}:${PORT3}"
    - "${PORT3}:${PORT3}/udp"
    - "${PORT4}:${PORT4}"
    - "${PORT4}:${PORT4}/udp"
    - "10080:10080/tcp"
    - "10081:10081/tcp"

7daystodie-datavolume:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: ${host_label}
    io.rancher.container.start_once: true
  volume_driver: ${VOLUME_DRIVER}
  volumes:
    - ${VOLUME_NAME}:/home/steam
  image: thalhalla/7daystodie:${7DAYSTODIE_BRANCH}
  command: /bin/true
