7daystodie:
  image: thalhalla/7daystodie:${7DAYSTODIE_BRANCH}
  command: ${7DAYSTODIE_COMMAND}
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    STEAM_FORCE_INSTALL: ${STEAM_FORCE_INSTALL}
    MAX_PLAYERS: ${MAX_PLAYERS}
    ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    HOSTNAME: ${HOSTNAME}
    STEAM_GID: 233780
    IP: ${IP}
    PORT: ${PORT}
    CLIENT_IP: 10.42.227.77
    MODS: ${7DAYSTODIE_MODS}
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.requested_ip: 10.42.227.77
    io.rancher.sidekicks: 7daystodie-datavolume
    io.rancher.container.pull_image: always
  volumes_from:
    - 7daystodie-datavolume
  ports:
    - "${PORT}:${PORT}/udp"
    - "2303:2303/udp"
    - "2304:2304/udp"
    - "2305:2305/udp"
7daystodie-datavolume:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volume_driver: ${VOLUME_DRIVER}
  volumes:
    - ${VOLUME_NAME}:/home/steam
  image: thalhalla/7daystodie:${7DAYSTODIE_BRANCH}
  command: /bin/true
