dockarmaiiipdg:
  image: thalhalla/dockarmaiii:${DOCKARMAIII_BRANCH}
  command: ${DOCKARMAIII_COMMAND}
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    GAME_PASSWORD: ${GAME_PASSWORD}
    HOSTNAME: ${HOSTNAME}
    STEAM_GID: 233780
    IP: ${IP}
    PORT: ${PORT}
    PORT2: ${PORT2}
    PORT3: ${PORT3}
    PORT4: ${PORT4}
    CLIENT_IP: 10.42.227.21
    CLIENT_IP2: 10.42.227.22
    CLIENT_IP3: 10.42.227.23
    CLIENT_IP4: 10.42.227.24
    CLIENT_IP5: 10.42.227.25
    CLIENT_IP6: 10.42.227.26
    MODS: ${DOCKARMAIII_MODS}
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.requested_ip: 10.42.227.27
    io.rancher.sidekicks: dockarmaiiipdg-datavolume
  volumes_from:
    - dockarmaiiipdg-datavolume
  ports:
    - "${PORT}:${PORT}/udp"
    - "2303:2303/udp"
    - "2304:2304/udp"
    - "2305:2305/udp"
dockarmaiiipdghc1:
  image: thalhalla/dockarmaiii:${DOCKARMAIII_BRANCH}
  command: /assets/baked-headless-pw.sh
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    GAME_PASSWORD: ${GAME_PASSWORD}
    STEAM_GID: 233780
    IP: ${IP}
    PORT: ${PORT}
    PORT2: ${PORT2}
    PORT3: ${PORT3}
    PORT4: ${PORT4}
    SERVER_IP: 10.42.227.27
    SERVER_PORT: 2302
  labels:
    io.rancher.container.requested_ip: 10.42.227.21
    io.rancher.sidekicks: dockarmaiiipdg-datavolume
  volumes_from:
    - dockarmaiiipdg-datavolume
dockarmaiiipdghc2:
  image: thalhalla/dockarmaiii:${DOCKARMAIII_BRANCH}
  command: /assets/baked-headless-pw.sh
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    GAME_PASSWORD: ${GAME_PASSWORD}
    STEAM_GID: 233780
    IP: ${IP}
    PORT: ${PORT}
    PORT2: ${PORT2}
    PORT3: ${PORT3}
    PORT4: ${PORT4}
    SERVER_IP: 10.42.227.27
    SERVER_PORT: 2302
  labels:
    io.rancher.container.requested_ip: 10.42.227.22
    io.rancher.sidekicks: dockarmaiiipdg-datavolume
  volumes_from:
    - dockarmaiiipdg-datavolume
dockarmaiiipdghc3:
  image: thalhalla/dockarmaiii:${DOCKARMAIII_BRANCH}
  command: /assets/baked-headless-pw.sh
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    GAME_PASSWORD: ${GAME_PASSWORD}
    STEAM_GID: 233780
    IP: ${IP}
    PORT: ${PORT}
    PORT2: ${PORT2}
    PORT3: ${PORT3}
    PORT4: ${PORT4}
    SERVER_IP: 10.42.227.27
    SERVER_PORT: 2302
  labels:
    io.rancher.container.requested_ip: 10.42.227.23
    io.rancher.sidekicks: dockarmaiiipdg-datavolume
  volumes_from:
    - dockarmaiiipdg-datavolume
dockarmaiiipdghc4:
  image: thalhalla/dockarmaiii:${DOCKARMAIII_BRANCH}
  command: /assets/baked-headless-pw.sh
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    GAME_PASSWORD: ${GAME_PASSWORD}
    STEAM_GID: 233780
    IP: ${IP}
    PORT: ${PORT}
    PORT2: ${PORT2}
    PORT3: ${PORT3}
    PORT4: ${PORT4}
    SERVER_IP: 10.42.227.27
    SERVER_PORT: 2302
  labels:
    io.rancher.container.requested_ip: 10.42.227.24
    io.rancher.sidekicks: dockarmaiiipdg-datavolume
  volumes_from:
    - dockarmaiiipdg-datavolume
dockarmaiiipdghc5:
  image: thalhalla/dockarmaiii:${DOCKARMAIII_BRANCH}
  command: /assets/baked-headless-pw.sh
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    GAME_PASSWORD: ${GAME_PASSWORD}
    STEAM_GID: 233780
    IP: ${IP}
    PORT: ${PORT}
    PORT2: ${PORT2}
    PORT3: ${PORT3}
    PORT4: ${PORT4}
    SERVER_IP: 10.42.227.27
    SERVER_PORT: 2302
  labels:
    io.rancher.container.requested_ip: 10.42.227.25
    io.rancher.sidekicks: dockarmaiiipdg-datavolume
  volumes_from:
    - dockarmaiiipdg-datavolume
dockarmaiiipdghc6:
  image: thalhalla/dockarmaiii:${DOCKARMAIII_BRANCH}
  command: /assets/baked-headless-pw.sh
  environment:
    STEAM_USERNAME: ${STEAM_USERNAME}
    STEAM_PASSWORD: ${STEAM_PASSWORD}
    GAME_PASSWORD: ${GAME_PASSWORD}
    STEAM_GID: 233780
    IP: ${IP}
    PORT: ${PORT}
    PORT2: ${PORT2}
    PORT3: ${PORT3}
    PORT4: ${PORT4}
    SERVER_IP: 10.42.227.27
    SERVER_PORT: 2302
  labels:
    io.rancher.container.requested_ip: 10.42.227.26
    io.rancher.sidekicks: dockarmaiiipdg-datavolume
  volumes_from:
    - dockarmaiiipdg-datavolume
dockarmaiiipdg-datavolume:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volume_driver: ${VOLUME_DRIVER}
  volumes:
    - ${VOLUME_NAME}:/home/steam
  image: thalhalla/dockarmaiii:${DOCKARMAIII_BRANCH}
  command: /bin/true
